name: Java CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # 或者 'zulu', 'adopt', 'openjdk' 等
        java-version: '21'

    - name: Generate Gradle Wrapper
      run: gradle wrapper

    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
